<?php

namespace ContainerCSt2LnA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4F1yuVnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4F1yuVn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4F1yuVn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', true],
        ], [
            'doctrine' => '?',
            'serializer' => '?',
        ]);
    }
}
