<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAwfneRI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAwfneRI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAwfneRI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAwfneRI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAwfneRI\App_KernelDevDebugContainer([
    'container.build_hash' => 'AwfneRI',
    'container.build_id' => '465c54a2',
    'container.build_time' => 1644614318,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAwfneRI');
