<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCSt2LnA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCSt2LnA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCSt2LnA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCSt2LnA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCSt2LnA\App_KernelDevDebugContainer([
    'container.build_hash' => 'CSt2LnA',
    'container.build_id' => '4b98d8cb',
    'container.build_time' => 1644269574,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCSt2LnA');
