<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'addRegion' => [['data'], ['_controller' => 'App\\Controller\\AdminController::addRegion'], [], [['variable', '/', '[^/]++', 'data', true], ['text', '/addRegion']], [], [], []],
    'showAllRegion' => [[], ['_controller' => 'App\\Controller\\AdminController::showRegion'], [], [['text', '/showRegion']], [], [], []],
    'showRegionByID' => [['id'], ['_controller' => 'App\\Controller\\AdminController::showRegionByID'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/showRegionByID']], [], [], []],
    'addBank' => [['data'], ['_controller' => 'App\\Controller\\AdminController::addBank'], [], [['variable', '/', '[^/]++', 'data', true], ['text', '/addBank']], [], [], []],
    'showAllBank' => [[], ['_controller' => 'App\\Controller\\AdminController::showBank'], [], [['text', '/showBank']], [], [], []],
    'showBankByID' => [['id'], ['_controller' => 'App\\Controller\\AdminController::showBankByID'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/showBankByID']], [], [], []],
    'addAgence' => [['data'], ['_controller' => 'App\\Controller\\AdminController::addAgence'], [], [['variable', '/', '[^/]++', 'data', true], ['text', '/addAgence']], [], [], []],
    'showAllAgence' => [[], ['_controller' => 'App\\Controller\\AdminController::showagence'], [], [['text', '/showAgence']], [], [], []],
    'showAgenceByID' => [['id', 'region'], ['_controller' => 'App\\Controller\\AdminController::showAgenceByBankRegion'], [], [['variable', '/', '[^/]++', 'region', true], ['variable', '/', '[^/]++', 'id', true], ['text', '/showAgenceByBankRegion']], [], [], []],
    'test' => [[], ['_controller' => 'App\\Controller\\BankController::test'], [], [['text', '/test']], [], [], []],
    'addFile' => [['data'], ['_controller' => 'App\\Controller\\BankController::addFile'], [], [['variable', '/', '[^/]++', 'data', true], ['text', '/addFile']], [], [], []],
    'showAllFile' => [[], ['_controller' => 'App\\Controller\\BankController::showFile'], [], [['text', '/showFile']], [], [], []],
    'showFileByID' => [['id'], ['_controller' => 'App\\Controller\\BankController::showAgenceByID'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/showFileByID']], [], [], []],
    'addTicket' => [['data'], ['_controller' => 'App\\Controller\\BankController::addTicket'], [], [['variable', '/', '[^/]++', 'data', true], ['text', '/addTicket']], [], [], []],
];
