<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'addRegion' => [['data'], ['_controller' => 'App\\Controller\\AdminController::addRegion'], [], [['variable', '/', '[^/]++', 'data', true], ['text', '/addRegion']], [], [], []],
    'showAllRegion' => [[], ['_controller' => 'App\\Controller\\AdminController::showRegion'], [], [['text', '/showRegion']], [], [], []],
    'showRegionByID' => [['id'], ['_controller' => 'App\\Controller\\AdminController::showRegionByID'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/showRegionByID']], [], [], []],
    'addBank' => [['data'], ['_controller' => 'App\\Controller\\AdminController::addBank'], [], [['variable', '/', '[^/]++', 'data', true], ['text', '/addBank']], [], [], []],
    'showAllBank' => [[], ['_controller' => 'App\\Controller\\AdminController::showBank'], [], [['text', '/showBank']], [], [], []],
    'showBankByID' => [['id'], ['_controller' => 'App\\Controller\\AdminController::showBankByID'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/showBankByID']], [], [], []],
    'test' => [[], ['_controller' => 'App\\Controller\\BankController::test'], [], [['text', '/test']], [], [], []],
];
